
POST /test/schemas/duplicated_uuid_field

{
	"_schema": {
		"schema": {
			"_id": {
				"_type": "uuid",
			},
			"<uuid_field>": {
				"_type": "keyword",
			},
		}
	},
	"~3pZyPcFqGq": "A",
	"00000000-0000-1000-8000-c97562616c75": "B",
	"urn:uuid:00000000-0000-1000-8000-c97562616c75": "C",
	"{00000000-0000-1000-8000-c97562616c75}": "D",
}
###
GET /test/duplicated_uuid_field/:schema
###


POST /test/duplicated_array_field

{
	"_schema": {
		"schema": {
			"_id": {
				"_type": "uuid",
			},
			"types": {
				"_type": "array/keyword",
			},
		}
	},
	"types": [
		"A",
		"B",
		"C",
		"D"
	]
}
###
GET /test/duplicated_array_field/:schema
###



PUT /test/merges/german

{
	"name": "German M. Bravo",
	"age": 39,
	"gender": "M"
}
###
MERGE /test/merges/german

{
	"name": "German Mendez Bravo"
}
###
GET /test/merges/:schema
###



PUT /test/accuracy/all

{
	"point": {
		"_point": {
			"_latitude": 19.32,
			"_longitude": 99.55
		},
		"_accuracy": [10, 15]
	},
	"date": {
		"_date": {
			"_year": 2016,
			"_month": 10,
			"_day": 25,
		},
		"_accuracy": [3600, "century"]
	},
}
###
GET /test/accuracy/:schema
###



PUT /test/keyword_id/1

{
    "_id": {
        "_type": "keyword"
    },
    "test": "Test 1"
}
###
PUT /test/keyword_id/2

{
    "test": "Test 2"
}
###
GET /test/keyword_id/:schema
###
