POST http://localhost:8880/test/schemas/duplicated_uuid_field
Accept: application/json; indent=4
Content-Type: application/json

{
	"_schema": {
		"schema": {
			"_id": {
				"_type": "uuid",
			},
			"<uuid_field>": {
				"_type": "keyword",
			},
		}
	},
	"~3pZyPcFqGq": "A",
	"00000000-0000-1000-8000-c97562616c75": "B",
	"urn:uuid:00000000-0000-1000-8000-c97562616c75": "C",
	"{00000000-0000-1000-8000-c97562616c75}": "D",
}
###
GET http://localhost:8880/test/duplicated_uuid_field/:schema
Accept: application/json; indent=4
###


POST http://localhost:8880/test/duplicated_array_field
Accept: application/json; indent=4
Content-Type: application/json

{
	"_schema": {
		"schema": {
			"_id": {
				"_type": "uuid",
			},
			"types": {
				"_type": "array/keyword",
			},
		}
	},
	"types": [
		"A",
		"B",
		"C",
		"D"
	]
}
###
GET http://localhost:8880/test/duplicated_array_field/:schema
Accept: application/json; indent=4
###



PUT http://localhost:8880/test/merges/german
Accept: application/json; indent=4
Content-Type: application/json

{
	"name": "German M. Bravo",
	"age": 39,
	"gender": "M"
}
###
MERGE http://localhost:8880/test/merges/german
Accept: application/json; indent=4
Content-Type: application/json

{
	"name": "German Mendez Bravo"
}
###
GET http://localhost:8880/test/merges/:schema
Accept: application/json; indent=4
###



PUT http://localhost:8880/test/accuracy/all
Accept: application/json; indent=4
Content-Type: application/json

{
	"point": {
		"_point": {
			"_latitude": 19.32,
			"_longitude": 99.55
		},
		"_accuracy": [10, 15]
	},
	"date": {
		"_date": {
			"_year": 2016,
			"_month": 10,
			"_day": 25,
		},
		"_accuracy": [3600, "century"]
	},
}
###
GET http://localhost:8880/test/accuracy/:schema
Accept: application/json; indent=4
###



PUT http://localhost:8880/test/keyword_id/1
Accept: application/json; indent=4
Content-Type: application/json

{
    "_id": {
        "_type": "keyword"
    },
    "test": "Test 1"
}
###
PUT http://localhost:8880/test/keyword_id/2
Accept: application/json; indent=4
Content-Type: application/json

{
    "test": "Test 2"
}
###
GET http://localhost:8880/test/keyword_id/:schema
Accept: application/json; indent=4
###
