POST http://localhost:8880/test/schemas/implicit-foreign-_schema
Accept: application/json; indent=4
Content-Type: application/json

{
	"_schema": {
		"_type": "foreign/object",
		"_endpoint": "test/schemas/implicit-foreign-_schema/.schemas/00000000-0000-1000-8000-010000000000",
		"_id": {
			"_type": "uuid",
		},
		"description": "Descripcion",
	},
	"_id": {
		"_type": "uuid",
	},
	"campo": {
		"_type": "string",
		"_value": "valor"
	},
}
###
GET http://localhost:8880/test/schemas/implicit-foreign-_schema/:schema
Accept: application/json; indent=4
###
GET http://localhost:8880/test/schemas/implicit-foreign-_schema/:metadata
Accept: application/json; indent=4
###
GET http://localhost:8880/test/schemas/implicit-foreign-_schema/.schemas/00000000-0000-1000-8000-010000000000
Accept: application/json; indent=4
###
GET http://localhost:8880/test/schemas/implicit-foreign-_schema/.schemas/:metadata
Accept: application/json; indent=4
###





POST http://localhost:8880/test/schemas/implicit-foreign-_schema
Accept: application/json; indent=4
Content-Type: application/json

{
	"_schema": "test/schemas/implicit-foreign-_schema/.schemas/00000000-0000-1000-8000-010000000000",
	"campo": "valor"
}
###
GET http://localhost:8880/test/schemas/implicit-foreign-_schema/:schema
Accept: application/json; indent=4
###
GET http://localhost:8880/test/schemas/implicit-foreign-_schema/:metadata
Accept: application/json; indent=4
###
GET http://localhost:8880/test/schemas/implicit-foreign-_schema/.schemas/00000000-0000-1000-8000-010000000000
Accept: application/json; indent=4
###
GET http://localhost:8880/test/schemas/implicit-foreign-_schema/.schemas/:schema
Accept: application/json; indent=4
###
GET http://localhost:8880/test/schemas/implicit-foreign-_schema/.schemas/:metadata
Accept: application/json; indent=4
###

PUT http://localhost:8880/test/schemas/implicit-foreign-_schema2/:schema
Accept: application/json; indent=4
Content-Type: application/json

{
	"_type": "foreign/object",
	"_endpoint": "test/schemas/implicit-foreign-_schema/.schemas/00000000-0000-1000-8000-010000000000",
	"_id": {
		"_type": "uuid",
	},
	"description": "Descripcion"
}
###
PUT http://localhost:8880/test/schemas/implicit-foreign-_schema2/:schema
Accept: application/json; indent=4
Content-Type: application/json

{
	"schema": {
		"_type": "object",
		"_id": {
			"_type": "uuid",
		},
		"campo": {
			"_type": "string"
		},
		"otro": {
			"_type": "integer"
		}
	},
}
###
GET http://localhost:8880/test/schemas/implicit-foreign-_schema2/:schema
Accept: application/json; indent=4
###
GET http://localhost:8880/test/schemas/implicit-foreign-_schema2/:metadata
Accept: application/json; indent=4
###
GET http://localhost:8880/test/schemas/implicit-foreign-_schema/.schemas/00000000-0000-1000-8000-010000000000
Accept: application/json; indent=4
###






POST http://localhost:8880/test/schemas/implicit-foreign-_type-_schema
Accept: application/json; indent=4
Content-Type: application/json

{
	"_schema": {
		"_type": "foreign/object",
		"_endpoint": "test/schemas/implicit-foreign-_type-_schema/.schemas/00000000-0000-1000-8000-010000000000",
		"_id": {
			"_type": "uuid",
		},
		"description": "Descripcion"
	},
	"campo": "valor"
}
###
GET http://localhost:8880/test/schemas/implicit-foreign-_type-_schema/:schema
Accept: application/json; indent=4
###
GET http://localhost:8880/test/schemas/implicit-foreign-_type-_schema/:metadata
Accept: application/json; indent=4
###
GET http://localhost:8880/test/schemas/implicit-foreign-_type-_schema/.schemas/00000000-0000-1000-8000-010000000000
Accept: application/json; indent=4
###






POST http://localhost:8880/test/schemas/implicit-foreign-_type-_schema-schema
Accept: application/json; indent=4
Content-Type: application/json

{
	"_schema": {
		"_type": "foreign/object",
		"_endpoint": "test/schemas/implicit-foreign-_type-_schema-schema/.schemas/00000000-0000-1000-8000-010000000000",
		"_id": {
			"_type": "uuid",
		},
		"description": "Descripcion",
		"schema": {
			"_type": "object",
			"_id": {
				"_type": "uuid",
			},
			"campo": {
				"_type": "string"
			}
		}
	},
	"campo": "valor"
}
###
GET http://localhost:8880/test/schemas/implicit-foreign-_type-_schema-schema/:schema
Accept: application/json; indent=4
###
GET http://localhost:8880/test/schemas/implicit-foreign-_type-_schema-schema/:metadata
Accept: application/json; indent=4
###
GET http://localhost:8880/test/schemas/implicit-foreign-_type-_schema-schema/.schemas/00000000-0000-1000-8000-010000000000
Accept: application/json; indent=4
###






POST http://localhost:8880/test/schemas/implicit-_schema-schema
Accept: application/json; indent=4
Content-Type: application/json

{
	"_schema": {
		"schema": {
			"_type": "object",
			"_id": {
				"_type": "uuid",
			},
			"campo": {
				"_type": "string"
			}
		}
	},
	"campo": "valor"
}
###
GET http://localhost:8880/test/schemas/implicit-_schema-schema/:schema
Accept: application/json; indent=4
###
GET http://localhost:8880/test/schemas/implicit-_schema-schema/:metadata
Accept: application/json; indent=4
###






POST http://localhost:8880/test/schemas/implicit
Accept: application/json; indent=4
Content-Type: application/json

{
	"campo": "valor"
}
###
GET http://localhost:8880/test/schemas/implicit/:schema
Accept: application/json; indent=4
###
GET http://localhost:8880/test/schemas/implicit/:metadata
Accept: application/json; indent=4
###






POST http://localhost:8880/test/schemas/implicit-_type
Accept: application/json; indent=4
Content-Type: application/json

{
	"_id": {
		"_type": "uuid",
	},
	"campo": {
		"_type": "string",
		"_value": "valor"
	}
}
###
GET http://localhost:8880/test/schemas/implicit-_type/:schema
Accept: application/json; indent=4
###
GET http://localhost:8880/test/schemas/implicit-_type/:metadata
Accept: application/json; indent=4
###






PUT http://localhost:8880/test/schemas/explicit-foreign/:schema
Accept: application/json; indent=4
Content-Type: application/json

"test/schemas/explicit-foreign/.schemas/00000000-0000-1000-8000-010000000000"
###
GET http://localhost:8880/test/schemas/explicit-foreign/:schema
Accept: application/json; indent=4
###
GET http://localhost:8880/test/schemas/explicit-foreign/:metadata
Accept: application/json; indent=4
###
GET http://localhost:8880/test/schemas/explicit-foreign/.schemas/00000000-0000-1000-8000-010000000000
Accept: application/json; indent=4
###






PUT http://localhost:8880/test/schemas/explicit-foreign-_type/:schema
Accept: application/json; indent=4
Content-Type: application/json

{
	"_type": "foreign/object",
	"_endpoint": "test/schemas/explicit-foreign-_type/.schemas/00000000-0000-1000-8000-010000000000",
	"_id": {
		"_type": "uuid",
	},
	"description": "Descripcion"
}
###
GET http://localhost:8880/test/schemas/explicit-foreign-_type/:schema
Accept: application/json; indent=4
###
GET http://localhost:8880/test/schemas/explicit-foreign-_type/:metadata
Accept: application/json; indent=4
###
GET http://localhost:8880/test/schemas/explicit-foreign-_type/.schemas/00000000-0000-1000-8000-010000000000
Accept: application/json; indent=4
###






PUT http://localhost:8880/test/schemas/explicit-foreign-_type-schema/:schema
Accept: application/json; indent=4
Content-Type: application/json

{
	"_type": "foreign/object",
	"_endpoint": "test/schemas/explicit-foreign-_type-schema/.schemas/00000000-0000-1000-8000-010000000000",
	"_id": {
		"_type": "uuid",
	},
	"description": "Descripcion",
	"schema": {
		"_type": "object",
		"_id": {
			"_type": "uuid",
		},
		"campo": {
			"_type": "string"
		}
	},
}
###
GET http://localhost:8880/test/schemas/explicit-foreign-_type-schema/:schema
Accept: application/json; indent=4
###
GET http://localhost:8880/test/schemas/explicit-foreign-_type-schema/:metadata
Accept: application/json; indent=4
###
GET http://localhost:8880/test/schemas/explicit-foreign-_type-schema/.schemas/00000000-0000-1000-8000-010000000000
Accept: application/json; indent=4
###






PUT http://localhost:8880/test/schemas/explicit-_type/:schema
Accept: application/json; indent=4
Content-Type: application/json

{
	"schema": {
		"_type": "object",
		"_id": {
			"_type": "uuid",
		},
		"campo": {
			"_type": "string"
		}
	},
}
###
GET http://localhost:8880/test/schemas/explicit-_type/:schema
Accept: application/json; indent=4
###
GET http://localhost:8880/test/schemas/explicit-_type/:metadata
Accept: application/json; indent=4
###






PUT http://localhost:8880/test/schemas/explicit/:schema
Accept: application/json; indent=4
Content-Type: application/json

{
	"version": 2.0,
	"schema": {
		"_type": "object",
		"_id": {
			"_type": "uuid",
		},
		"campo": {
				"_index": "field_terms",
				"_language": "en",
				"_slot": 499030115,
				"_type": "string"
		}
	}
}
###
GET http://localhost:8880/test/schemas/explicit/:schema
Accept: application/json; indent=4
###
GET http://localhost:8880/test/schemas/explicit/:metadata
Accept: application/json; indent=4
###






PUT http://localhost:8880/test/schemas/explicit-foreign-_type-_schama-object/:schema
Accept: application/json; indent=4
Content-Type: application/json

{
	"_type": "foreign/object",
	"_endpoint": "test/schemas/explicit-foreign-_type-_schama-object/.schemas/00000000-0000-1000-8000-010000000000",
	"_id": {
		"_type": "uuid",
	},
	"description": "Descripcion"
}
###
PUT http://localhost:8880/test/schemas/explicit-foreign-_type-_schama-object/:schema
Accept: application/json; indent=4
Content-Type: application/json

{
	"schema": {
		"_type": "object",
		"_id": {
			"_type": "uuid",
		},
		"campo": {
			"_type": "string"
		}
	},
}
###
GET http://localhost:8880/test/schemas/explicit-foreign-_type-_schama-object/:schema
Accept: application/json; indent=4
###
GET http://localhost:8880/test/schemas/explicit-foreign-_type-_schama-object/:metadata
Accept: application/json; indent=4
###
GET http://localhost:8880/test/schemas/explicit-foreign-_type-_schama-object/.schemas/00000000-0000-1000-8000-010000000000
Accept: application/json; indent=4
###




PUT http://localhost:8880/test/schemas/explicit-foreign-_type-_schama-foreign_object/:schema
Accept: application/json; indent=4
Content-Type: application/json

{
	"_type": "foreign/object",
	"_endpoint": "test/schemas/explicit-foreign-_type-_schama-foreign_object/.schemas/00000000-0000-1000-8000-010000000000",
	"_id": {
		"_type": "uuid",
	},
	"description": "Descripcion",
	"schema": {
		"_type": "object",
		"_id": {
			"_type": "uuid",
		},
		"campo": {
			"_type": "string"
		},
		"otro": {
			"_type": "string"
		},
	},
}
###
GET http://localhost:8880/test/schemas/explicit-foreign-_type-_schama-foreign_object/:schema
Accept: application/json; indent=4
###
GET http://localhost:8880/test/schemas/explicit-foreign-_type-_schama-foreign_object/:metadata
Accept: application/json; indent=4
###
GET http://localhost:8880/test/schemas/explicit-foreign-_type-_schama-foreign_object/.schemas/00000000-0000-1000-8000-010000000000
Accept: application/json; indent=4
###




POST http://localhost:8880/test/schemas/uuid_field
Accept: application/json; indent=4
Content-Type: application/json

{
	"_schema": {
		"schema": {
			"_id": {
				"_type": "uuid",
			},
			"<uuid_field>": {
				"meta": {
					"_recurse": false,
				},
				"roles": {
					"_type": "array/keyword",
				}
			},
		}
	},
	"~3pZyPcFqGq": {
		"meta": {
			"scope": "read write"
		},
		"roles": [
			"myself"
		]
	},
}
###
GET http://localhost:8880/test/schemas/uuid_field/:schema
Accept: application/json; indent=4
###
GET http://localhost:8880/test/schemas/uuid_field/:metadata
Accept: application/json; indent=4
###

//////








POST http://localhost:8880/test/schemas/implicit-foreign-_schema
Accept: application/json; indent=4
Content-Type: application/json

{
	"_schema": {
		"_type": "foreign/object",
		"_endpoint": "test/schemas/implicit-foreign-_schema/.schemas/~8NB7DEPmtJ4",
		"_id": {
			"_type": "uuid",
		},
		"description": "Descripcion"
	},
	"_id": {
		"_type": "uuid",
	},
	"campo": {
		"_type": "string",
		"_value": "valor",
	},
}
###
GET http://localhost:8880/test/schemas/implicit-foreign-_schema/:schema
Accept: application/json; indent=4
###
GET http://localhost:8880/test/schemas/implicit-foreign-_schema/:metadata
Accept: application/json; indent=4
###
GET http://localhost:8880/test/schemas/implicit-foreign-_schema/.schemas/~8NB7DEPmtJ4
Accept: application/json; indent=4
###
GET http://localhost:8880/test/schemas/implicit-foreign-_schema/.schemas/:schema
Accept: application/json; indent=4
###
GET http://localhost:8880/test/schemas/implicit-foreign-_schema/.schemas/:metadata
Accept: application/json; indent=4
###



PUT http://localhost:8880/test/xxx/:schema
Accept: application/json; indent=4
Content-Type: application/json

{
		"version": 2.0,
		"description": "Descripcion",
		"schema": {
			"_type": "object",
			"campo": {
					"_prefix": "\xff\x03w\xcb",
					"_index": "terms",
					"_language": "en",
					"_slot": 3064504733,  // slot: '\xff\x03w\xcb' = 3064504733
					"_type": "string"
			},
			"_id": {
					"_bool_term": true,
					"_prefix": "Q",
					"_slot": 0,
					"_type": "uuid"
			}
		},
}
###
GET http://localhost:8880/test/xxx/:schema
Accept: application/json; indent=4
###
GET http://localhost:8880/test/xxx/:metadata
Accept: application/json; indent=4
###




PUT http://localhost:8880/test/xxx/:schema
Accept: application/json; indent=4
Content-Type: application/json

{
		"version": 2.0,
		"description": "Descripcion",
		"schema": {
				"campo": {
						"_index": "terms",
						"_language": "en",
						"_type": "string"
				},
				"_id": {
						"_bool_term": true,
						"_type": "uuid"
				}
		},
}
###
GET http://localhost:8880/test/xxx/:schema
Accept: application/json; indent=4
###
GET http://localhost:8880/test/xxx/:metadata
Accept: application/json; indent=4
###
