
POST /test/schemas/implicit-foreign-_schema

{
	"_schema": {
		"_type": "foreign/object",
		"_endpoint": "test/schemas/implicit-foreign-_schema/.schemas/00000000-0000-1000-8000-010000000000",
		"_id": {
			"_type": "uuid",
		},
		"description": "Descripcion",
	},
	"_id": {
		"_type": "uuid",
	},
	"campo": {
		"_type": "string",
		"_value": "valor"
	},
}
###
GET /test/schemas/implicit-foreign-_schema/:schema
###
GET /test/schemas/implicit-foreign-_schema/:metadata
###
GET /test/schemas/implicit-foreign-_schema/.schemas/00000000-0000-1000-8000-010000000000
###
GET /test/schemas/implicit-foreign-_schema/.schemas/:metadata
###





POST /test/schemas/implicit-foreign-_schema

{
	"_schema": "test/schemas/implicit-foreign-_schema/.schemas/00000000-0000-1000-8000-010000000000",
	"campo": "valor"
}
###
GET /test/schemas/implicit-foreign-_schema/:schema
###
GET /test/schemas/implicit-foreign-_schema/:metadata
###
GET /test/schemas/implicit-foreign-_schema/.schemas/00000000-0000-1000-8000-010000000000
###
GET /test/schemas/implicit-foreign-_schema/.schemas/:schema
###
GET /test/schemas/implicit-foreign-_schema/.schemas/:metadata
###

PUT /test/schemas/implicit-foreign-_schema2/:schema

{
	"_type": "foreign/object",
	"_endpoint": "test/schemas/implicit-foreign-_schema/.schemas/00000000-0000-1000-8000-010000000000",
	"_id": {
		"_type": "uuid",
	},
	"description": "Descripcion"
}
###
PUT /test/schemas/implicit-foreign-_schema2/:schema

{
	"schema": {
		"_type": "object",
		"_id": {
			"_type": "uuid",
		},
		"campo": {
			"_type": "string"
		},
		"otro": {
			"_type": "integer"
		}
	},
}
###
GET /test/schemas/implicit-foreign-_schema2/:schema
###
GET /test/schemas/implicit-foreign-_schema2/:metadata
###
GET /test/schemas/implicit-foreign-_schema/.schemas/00000000-0000-1000-8000-010000000000
###






POST /test/schemas/implicit-foreign-_type-_schema

{
	"_schema": {
		"_type": "foreign/object",
		"_endpoint": "test/schemas/implicit-foreign-_type-_schema/.schemas/00000000-0000-1000-8000-010000000000",
		"_id": {
			"_type": "uuid",
		},
		"description": "Descripcion"
	},
	"campo": "valor"
}
###
GET /test/schemas/implicit-foreign-_type-_schema/:schema
###
GET /test/schemas/implicit-foreign-_type-_schema/:metadata
###
GET /test/schemas/implicit-foreign-_type-_schema/.schemas/00000000-0000-1000-8000-010000000000
###






POST /test/schemas/implicit-foreign-_type-_schema-schema

{
	"_schema": {
		"_type": "foreign/object",
		"_endpoint": "test/schemas/implicit-foreign-_type-_schema-schema/.schemas/00000000-0000-1000-8000-010000000000",
		"_id": {
			"_type": "uuid",
		},
		"description": "Descripcion",
		"schema": {
			"_type": "object",
			"_id": {
				"_type": "uuid",
			},
			"campo": {
				"_type": "string"
			}
		}
	},
	"campo": "valor"
}
###
GET /test/schemas/implicit-foreign-_type-_schema-schema/:schema
###
GET /test/schemas/implicit-foreign-_type-_schema-schema/:metadata
###
GET /test/schemas/implicit-foreign-_type-_schema-schema/.schemas/00000000-0000-1000-8000-010000000000
###






POST /test/schemas/implicit-_schema-schema

{
	"_schema": {
		"schema": {
			"_type": "object",
			"_id": {
				"_type": "uuid",
			},
			"campo": {
				"_type": "string"
			}
		}
	},
	"campo": "valor"
}
###
GET /test/schemas/implicit-_schema-schema/:schema
###
GET /test/schemas/implicit-_schema-schema/:metadata
###






POST /test/schemas/implicit

{
	"campo": "valor"
}
###
GET /test/schemas/implicit/:schema
###
GET /test/schemas/implicit/:metadata
###






POST /test/schemas/implicit-_type

{
	"_id": {
		"_type": "uuid",
	},
	"campo": {
		"_type": "string",
		"_value": "valor"
	}
}
###
GET /test/schemas/implicit-_type/:schema
###
GET /test/schemas/implicit-_type/:metadata
###






PUT /test/schemas/explicit-foreign/:schema

"test/schemas/explicit-foreign/.schemas/00000000-0000-1000-8000-010000000000"
###
GET /test/schemas/explicit-foreign/:schema
###
GET /test/schemas/explicit-foreign/:metadata
###
GET /test/schemas/explicit-foreign/.schemas/00000000-0000-1000-8000-010000000000
###






PUT /test/schemas/explicit-foreign-_type/:schema

{
	"_type": "foreign/object",
	"_endpoint": "test/schemas/explicit-foreign-_type/.schemas/00000000-0000-1000-8000-010000000000",
	"_id": {
		"_type": "uuid",
	},
	"description": "Descripcion"
}
###
GET /test/schemas/explicit-foreign-_type/:schema
###
GET /test/schemas/explicit-foreign-_type/:metadata
###
GET /test/schemas/explicit-foreign-_type/.schemas/00000000-0000-1000-8000-010000000000
###






PUT /test/schemas/explicit-foreign-_type-schema/:schema

{
	"_type": "foreign/object",
	"_endpoint": "test/schemas/explicit-foreign-_type-schema/.schemas/00000000-0000-1000-8000-010000000000",
	"_id": {
		"_type": "uuid",
	},
	"description": "Descripcion",
	"schema": {
		"_type": "object",
		"_id": {
			"_type": "uuid",
		},
		"campo": {
			"_type": "string"
		}
	},
}
###
GET /test/schemas/explicit-foreign-_type-schema/:schema
###
GET /test/schemas/explicit-foreign-_type-schema/:metadata
###
GET /test/schemas/explicit-foreign-_type-schema/.schemas/00000000-0000-1000-8000-010000000000
###






PUT /test/schemas/explicit-_type/:schema

{
	"schema": {
		"_type": "object",
		"_id": {
			"_type": "uuid",
		},
		"campo": {
			"_type": "string"
		}
	},
}
###
GET /test/schemas/explicit-_type/:schema
###
GET /test/schemas/explicit-_type/:metadata
###






PUT /test/schemas/explicit/:schema

{
	"version": 2.0,
	"schema": {
		"_type": "object",
		"_id": {
			"_type": "uuid",
		},
		"campo": {
				"_index": "field_terms",
				"_language": "en",
				"_slot": 499030115,
				"_type": "string"
		}
	}
}
###
GET /test/schemas/explicit/:schema
###
GET /test/schemas/explicit/:metadata
###






PUT /test/schemas/explicit-foreign-_type-_schama-object/:schema

{
	"_type": "foreign/object",
	"_endpoint": "test/schemas/explicit-foreign-_type-_schama-object/.schemas/00000000-0000-1000-8000-010000000000",
	"_id": {
		"_type": "uuid",
	},
	"description": "Descripcion"
}
###
PUT /test/schemas/explicit-foreign-_type-_schama-object/:schema

{
	"schema": {
		"_type": "object",
		"_id": {
			"_type": "uuid",
		},
		"campo": {
			"_type": "string"
		}
	},
}
###
GET /test/schemas/explicit-foreign-_type-_schama-object/:schema
###
GET /test/schemas/explicit-foreign-_type-_schama-object/:metadata
###
GET /test/schemas/explicit-foreign-_type-_schama-object/.schemas/00000000-0000-1000-8000-010000000000
###




PUT /test/schemas/explicit-foreign-_type-_schama-foreign_object/:schema

{
	"_type": "foreign/object",
	"_endpoint": "test/schemas/explicit-foreign-_type-_schama-foreign_object/.schemas/00000000-0000-1000-8000-010000000000",
	"_id": {
		"_type": "uuid",
	},
	"description": "Descripcion",
	"schema": {
		"_type": "object",
		"_id": {
			"_type": "uuid",
		},
		"campo": {
			"_type": "string"
		},
		"otro": {
			"_type": "string"
		},
	},
}
###
GET /test/schemas/explicit-foreign-_type-_schama-foreign_object/:schema
###
GET /test/schemas/explicit-foreign-_type-_schama-foreign_object/:metadata
###
GET /test/schemas/explicit-foreign-_type-_schama-foreign_object/.schemas/00000000-0000-1000-8000-010000000000
###




POST /test/schemas/uuid_field

{
	"_schema": {
		"schema": {
			"_id": {
				"_type": "uuid",
			},
			"<uuid_field>": {
				"meta": {
					"_recurse": false,
				},
				"roles": {
					"_type": "array/keyword",
				}
			},
		}
	},
	"~3pZyPcFqGq": {
		"meta": {
			"scope": "read write"
		},
		"roles": [
			"myself"
		]
	},
}
###
GET /test/schemas/uuid_field/:schema
###
GET /test/schemas/uuid_field/:metadata
###

//////








POST /test/schemas/implicit-foreign-_schema

{
	"_schema": {
		"_type": "foreign/object",
		"_endpoint": "test/schemas/implicit-foreign-_schema/.schemas/~8NB7DEPmtJ4",
		"_id": {
			"_type": "uuid",
		},
		"description": "Descripcion"
	},
	"_id": {
		"_type": "uuid",
	},
	"campo": {
		"_type": "string",
		"_value": "valor",
	},
}
###
GET /test/schemas/implicit-foreign-_schema/:schema
###
GET /test/schemas/implicit-foreign-_schema/:metadata
###
GET /test/schemas/implicit-foreign-_schema/.schemas/~8NB7DEPmtJ4
###
GET /test/schemas/implicit-foreign-_schema/.schemas/:schema
###
GET /test/schemas/implicit-foreign-_schema/.schemas/:metadata
###



PUT /test/xxx/:schema

{
	"version": 2.0,
	"description": "Descripcion",
	"schema": {
		"_type": "object",
		"campo": {
			"_prefix": "\xff\x03w\xcb",
			"_index": "terms",
			"_language": "en",
			"_slot": 3064504733,  // slot: '\xff\x03w\xcb' = 3064504733
			"_type": "string"
		},
		"_id": {
			"_bool_term": true,
			"_prefix": "Q",
			"_slot": 0,
			"_type": "uuid"
		}
	},
}
###
GET /test/xxx/:schema
###
GET /test/xxx/:metadata
###




PUT /test/xxx/:schema

{
	"version": 2.0,
	"description": "Descripcion",
	"schema": {
		"campo": {
			"_index": "terms",
			"_language": "en",
			"_type": "string"
		},
		"_id": {
			"_bool_term": true,
			"_type": "uuid"
		}
	},
}
###
GET /test/xxx/:schema
###
GET /test/xxx/:metadata
###




POST /test/schemas/namespace

{
	"A": {
		"_namespace": true,
		"_value": "A de árbol"
	},

	"B": {
		"_namespace": true,
		"_value": "B de barco"
	},

	"C": {
		"_namespace": true,
		"_value": "C de casa",
		"D": {
			"_value": "D de dedo",
			"E": {
				"_value": [
					"E de Espada",
					null
				]
			}
		}
	}
}
###
GET /test/schemas/namespace/:schema
###
GET /test/schemas/namespace/:metadata
###
