
PUT /text/J

{
	"_id": {
		"_type": "keyword"
	}
}
###


PUT /text/J

{
	"_id": {
		"_type": "keyword"
	},
	"cnt": {
		"_type": "integer",
		"_value": 0
	},
	"_script": {
		"_type": "chai",
		"_value": "folios.chai",
		"_body": "def on_put(new_obj, old_obj) { if (old_obj) { new_obj[\"cnt\"] = old_obj[\"cnt\"] + 1; } return new_obj; }"
	}
}
###


PUT /text/J

{
	"_script": "folios.chai"
}
###






{
	"_schema": {
		"_type": "foreign/schema",
		"_value": "path/to/schema"
	},



	"_script": {
		"_type": "foreign/chai",
		"_value": "xapiand://localhost:8880/path/to/nombre.chai"
	},
	"_script": {
		"_type": "foreign/chai",
		"_value": "path/to/nombre.chai"
	},
	"_script": {
		"_type": "foreign/chai",
		"_value": "file:///path/to/nombre.chai"
	},
	"_script": {
		"_type": "foreign/chai",
		"_value": "http://domain.com/path/to/nombre.chai"
	},



	"_script": {
		"_type": "chai",
		"_value": "nombre.chai",
		"_body": "def on_put(obj_new, obj_old) { if (!obj_old.empty()) { ++obj_old[\"folio\"]; return obj_old; } return obj_new; }"
	},
	"_script": {
		"_value": {
			"_chai": {
				"_value": "nombre.chai",
				"_body": "def on_put(obj_new, obj_old) { if (!obj_old.empty()) { ++obj_old[\"folio\"]; return obj_old; } return obj_new; }"
			}
		}
	},
	"_script": {
		"_chai": {
			"_value": "nombre.chai",
			"_body": "def on_put(obj_new, obj_old) { if (!obj_old.empty()) { ++obj_old[\"folio\"]; return obj_old; } return obj_new; }"
		}
	},
	"_script": {
		"_chai": "nombre.chai"
	},
	"_script": "nombre.chai",
	"_script": "script body here ... // nombre.chai"
}
