PUT http://localhost:8880/test/doc?commit
Accept: application/json; indent=4
Content-Type: application/json

{
	"_id": {
		"_type": "keyword",
	},
	"ident": {
		"_type": "uuid",
		"_index": "global_terms",
		"_value": "~notmet",
	},
}
###
GET http://localhost:8880/test/:schema
Accept: application/json; indent=4
###
GET http://localhost:8880/test/:metadata
Accept: application/json; indent=4
###
GET http://localhost:8880/test/:info/doc
Accept: application/json; indent=4
###
GET http://localhost:8880/test/:search?q=~notmet
Accept: application/json; indent=4
###



POST http://localhost:8880/test/A
Accept: application/json; indent=4
Content-Type: application/json

{
	"_schema": {
		"_type": "foreign/object",
		"_endpoint": "test/schemas/implicit-foreign-_schema/.schemas/00000000-0000-1000-8000-010000000000",
		"description": "Descripcion"
	},
	"_id": {
		"_type": "uuid",
	},
	"campo": {
		"_type": "string",
		"_value": "valor"
	},
	"roles": {
		"_type": "array/keyword",
		"_value": [
			null,  // <- there was an error when extracting _value from here
		],
	},
}
###



POST http://localhost:8880/test/schemas/implicit-_type
Accept: application/json; indent=4
Content-Type: application/json

{
	"_id": {
		"_type": "uuid",
	},
	"campo": {
		"_type": "string",
	}
}
###


POST http://localhost:8880/test/schemas/implicit-_type
Accept: application/json; indent=4
Content-Type: application/json

{
	"_id": {
		"_type": "uuid",
	},
	"campo": {
		"_type": "string",
		"_value": null,
	}
}
###


POST http://localhost:8880/test/schemas/implicit-_type
Accept: application/json; indent=4
Content-Type: application/json

{
	"_id": {
		"_type": "uuid",
	},
	"campo": {
		"otro": {
			"_type": "string",
		}
	}
}
###


POST http://localhost:8880/test/schemas/implicit-_type
Accept: application/json; indent=4
Content-Type: application/json

{
	"_id": {
		"_type": "uuid",
	},
	"campo": {
		"otro": {
			"_type": "string",
			"_value": null,
		}
	}
}
###



POST http://localhost:8880/test/A
Accept: application/json; indent=4
Content-Type: application/json

{
	"_recurse": false,
	"_id": {
		"_type": "uuid",
	},
	"#comment": "This comment is ignored",
	"schema": {
		"_type": "object",
	}
}
###
GET http://localhost:8880/test/A/:schema
Accept: application/json; indent=4
###
GET http://localhost:8880/test/A/::1
Accept: application/json; indent=4
###



//

PUT http://localhost:8880/test/feed_cache/A
Accept: application/json; indent=4
Content-Type: application/json

{
	"~notmet": {
		"roles": {
			"_type": "array/keyword",
			"_index": "all",
			"_value": [
				"myself",
				"any"
			],
		}
	}
}
###
PUT http://localhost:8880/test/feed_cache/B
Accept: application/json; indent=4
Content-Type: application/json

{
	"~3pZyPcFqGq": {
		"roles": {
			"_type": "array/keyword",
			"_index": "all",
			"_value": [
				"myself",
				"any"
			],
		}
	}
}
###
PUT http://localhost:8880/test/feed_cache/C
Accept: application/json; indent=4
Content-Type: application/json

{
	"~SsQg3rJrx3P": {
		"roles": {
			"_type": "array/keyword",
			"_index": "all",
			"_value": [
				"myself",
				"any"
			],
		}
	}
}
###
GET http://localhost:8880/test/feed_cache/:info/A?volatile
Accept: application/json; indent=4
###
GET http://localhost:8880/test/feed_cache/:info/B?volatile
Accept: application/json; indent=4
###
GET http://localhost:8880/test/feed_cache/:info/C?volatile
Accept: application/json; indent=4
###
