PUT /test/doc?commit
Host: localhost:8880
Accept: application/json; indent=4
Content-Type: application/json

{
	"_id": {
		"_type": "keyword",
	},
	"ident": {
		"_type": "uuid",
		"_index": "global_terms",
		"_value": "~notmet",
	},
}
###
GET /test/:schema
Host: localhost:8880
Accept: application/json; indent=4
###
GET /test/:metadata
Host: localhost:8880
Accept: application/json; indent=4
###
GET /test/:info/doc
Host: localhost:8880
Accept: application/json; indent=4
###
GET /test/:search?q=~notmet
Host: localhost:8880
Accept: application/json; indent=4
###



POST /test/A
Host: localhost:8880
Accept: application/json; indent=4
Content-Type: application/json

{
	"_schema": {
		"_type": "foreign/object",
		"_endpoint": "test/schemas/implicit-foreign-_schema/.schemas/00000000-0000-1000-8000-010000000000",
		"description": "Descripcion"
	},
	"_id": {
		"_type": "uuid",
	},
	"campo": {
		"_type": "string",
		"_value": "valor"
	},
	"roles": {
		"_type": "array/keyword",
		"_value": [
			null,  // <- there was an error when extracting _value from here
		],
	},
}
###



POST /test/schemas/implicit-_type
Host: localhost:8880
Accept: application/json; indent=4
Content-Type: application/json

{
	"_id": {
		"_type": "uuid",
	},
	"campo": {
		"_type": "string",
	}
}
###


POST /test/schemas/implicit-_type
Host: localhost:8880
Accept: application/json; indent=4
Content-Type: application/json

{
	"_id": {
		"_type": "uuid",
	},
	"campo": {
		"_type": "string",
		"_value": null,
	}
}
###


POST /test/schemas/implicit-_type
Host: localhost:8880
Accept: application/json; indent=4
Content-Type: application/json

{
	"_id": {
		"_type": "uuid",
	},
	"campo": {
		"otro": {
			"_type": "string",
		}
	}
}
###


POST /test/schemas/implicit-_type
Host: localhost:8880
Accept: application/json; indent=4
Content-Type: application/json

{
	"_id": {
		"_type": "uuid",
	},
	"campo": {
		"otro": {
			"_type": "string",
			"_value": null,
		}
	}
}
###



POST /test/A
Host: localhost:8880
Accept: application/json; indent=4
Content-Type: application/json

{
	"_recurse": false,
	"_id": {
		"_type": "uuid",
	},
	"#comment": "This comment is ignored",
	"schema": {
		"_type": "object",
	}
}
###
GET /test/A/:schema
Host: localhost:8880
Accept: application/json; indent=4
###
GET /test/A/::1
Host: localhost:8880
Accept: application/json; indent=4
###



//

PUT /test/feed_cache/A
Host: localhost:8880
Accept: application/json; indent=4
Content-Type: application/json

{
	"~notmet": {
		"roles": {
			"_type": "array/keyword",
			"_index": "all",
			"_value": [
				"myself",
				"any"
			],
		}
	}
}
###
PUT /test/feed_cache/B
Host: localhost:8880
Accept: application/json; indent=4
Content-Type: application/json

{
	"~3pZyPcFqGq": {
		"roles": {
			"_type": "array/keyword",
			"_index": "all",
			"_value": [
				"myself",
				"any"
			],
		}
	}
}
###
PUT /test/feed_cache/C
Host: localhost:8880
Accept: application/json; indent=4
Content-Type: application/json

{
	"~SsQg3rJrx3P": {
		"roles": {
			"_type": "array/keyword",
			"_index": "all",
			"_value": [
				"myself",
				"any"
			],
		}
	}
}
###
GET /test/feed_cache/:info/A?volatile
Host: localhost:8880
Accept: application/json; indent=4
###
GET /test/feed_cache/:info/B?volatile
Host: localhost:8880
Accept: application/json; indent=4
###
GET /test/feed_cache/:info/C?volatile
Host: localhost:8880
Accept: application/json; indent=4
###
