PUT /test/types/numeric
Host: localhost:8880
Accept: application/json; indent=4
Content-Type: application/json

{
    "positive": {
        "_type": "integer",
        "_value": 123456
    },
    "integer": {
        "_type": "integer",
        "_value": 123456
    },
    "float": {
        "_type": "float",
        "_value": 123456
    },
}
###
GET /test/types/:info/numeric
Host: localhost:8880
Accept: application/json; indent=4
###
GET /test/types/:schema
Host: localhost:8880
Accept: application/json; indent=4
###


PUT /test/types/string
Host: localhost:8880
Accept: application/json; indent=4
Content-Type: application/json

{
    "keyword": {
        "_type": "keyword",
        "_value": "The quick brown fox jumps over the lazy dog"
    },
    "string": {
        "_type": "string",
        "_value": "The quick brown fox jumps over the lazy dog"
    },
    "text": {
        "_type": "text",
        "_value": "The quick brown fox jumps over the lazy dog"
    },
}
###
GET /test/types/:info/string
Host: localhost:8880
Accept: application/json; indent=4
###
GET /test/types/:schema
Host: localhost:8880
Accept: application/json; indent=4
###
