
PUT /test/types/numeric

{
    "positive": {
        "_type": "integer",
        "_value": 123456
    },
    "integer": {
        "_type": "integer",
        "_value": 123456
    },
    "float": {
        "_type": "float",
        "_value": 123456
    },
}
###
GET /test/types/numeric:info
###
GET /test/types/:schema
###


PUT /test/types/string

{
    "keyword": {
        "_type": "keyword",
        "_value": "The quick brown fox jumps over the lazy dog"
    },
    "string": {
        "_type": "string",
        "_value": "The quick brown fox jumps over the lazy dog"
    },
    "text": {
        "_type": "text",
        "_value": "The quick brown fox jumps over the lazy dog"
    },
}
###
GET /test/types/string:info
###
GET /test/types/:schema
###
