PUT http://localhost:8880/test/uuids/00000000-0000-1000-8000-010000000000
Accept: application/json; indent=4
Content-Type: application/json

{
  "campo": "first"
}
###
GET http://localhost:8880/test/uuids/:schema
Accept: application/json; indent=4
###
GET http://localhost:8880/test/uuids/00000000-0000-1000-8000-010000000000
Accept: application/json; indent=4
###
GET http://localhost:8880/test/uuids/00000000-0000-1000-8000-010000000000|campo
Accept: application/json; indent=4
###
GET http://localhost:8880/test/uuids/~notmet
Accept: application/json; indent=4
###
GET http://localhost:8880/test/uuids/~notmet|campo
Accept: application/json; indent=4
###



PUT http://localhost:8880/test/uuids/00000000-0000-1000-8000-010000000000/00000000-0000-1000-8000-010000000000
Accept: application/json; indent=4
Content-Type: application/json

{
  "campo": "second"
}
###
GET http://localhost:8880/test/uuids/00000000-0000-1000-8000-010000000000/00000000-0000-1000-8000-010000000000
Accept: application/json; indent=4
###
GET http://localhost:8880/test/uuids/00000000-0000-1000-8000-010000000000/00000000-0000-1000-8000-010000000000|campo
Accept: application/json; indent=4
###
GET http://localhost:8880/test/uuids/~notmet/~notmet
Accept: application/json; indent=4
###
GET http://localhost:8880/test/uuids/~notmet/~notmet|campo
Accept: application/json; indent=4
###
GET http://localhost:8880/test/uuids/~not/me/t/~notmet
Accept: application/json; indent=4
###
GET http://localhost:8880/test/uuids/~not/me/t/~notmet|campo
Accept: application/json; indent=4
###


PUT http://localhost:8880/test/uuids/00000000-0000-1000-8000-010000000000/230c0800-dc3c-11e7-b966-a3ab262e682b
Accept: application/json; indent=4
Content-Type: application/json

{
  "campo": "third"
}
###


PUT http://localhost:8880/test/uuids/00000000-0000-1000-8000-010000000000/60579016-dec5-11e7-b616-34363bc9ddd6
Accept: application/json; indent=4
Content-Type: application/json

{
  "campo": "fourth"
}
###


PUT http://localhost:8880/test/uuids/00000000-0000-1000-8000-010000000000/5759b016-10c0-4526-a981-47d6d19f6fb4
Accept: application/json; indent=4
Content-Type: application/json

{
  "campo": "fifth"
}
###


POST http://localhost:8880/test/uuids/00000000-0000-1000-8000-010000000000
Accept: application/json; indent=4
Content-Type: application/json

{
  "campo": "sixth"
}
###
